### ISSUE TITLE
PHP Version Old

### ISSUE THREAD

**Issue by 0xliam627** [jasonw4331/libpmquery#12]
### Issue description

- Expected result: Composer downloaded successfully
- Actual result: Composer downloaded failed

### Steps to reproduce the issue

1. Use command `composer require jasonw4331/libpmquery`

### OS and versions

* PocketMine-MP: 5.0.0
* PHP: 8.2.6
* Game version: 1.19.80

### Console error, backtrace or other files

![image](https://github.com/jasonw4331/libpmquery/assets/70517151/d31be279-96b1-4983-95f0-54348fd1d826)

**Comment by jasonw4331** [comment]
Fixed in 0412634c5f5f1e47f340feb3b8bfa31491d5642a
