### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by ghost** [jasonw4331/libpmquery#2]
Can you create one ExemplePlugin with API for get Count of Players from one Server?

e.g: PMQuery::getPlayers(IP, PORT);

And etc.

**Comment by jasonw4331** [comment]
https://github.com/jasonwynn10/Other-Plugins/tree/master/CrossOnlineCount
https://poggit.pmmp.io/ci/jasonwynn10/CrossOnlineCount/CrossOnlineCount

**Comment by ghost** [comment]
@jasonwynn10 Not for slapper. It's different.

One time you changed name of slapper, and other time when you update MOTD.

**Comment by jasonwynn10** [comment]
hmm

**Comment by ghost** [comment]
Ok, thanks bro.
